/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'on-surface': '#d9e3f2',
        error: '#ffb4ab',
        'inverse-surface': '#d9e3f2',
        'on-secondary-fixed': '#1c1c18',
        'on-secondary-container': '#b8b5ae',
        'inverse-primary': '#bd0c2d',
        'secondary-container': '#484742',
        'on-error-container': '#ffdad6',
        'on-primary': '#680013',
        'surface-container-high': '#212b35',
        'on-tertiary-fixed-variant': '#00513c',
        'on-primary-container': '#5b000f',
        'on-tertiary': '#003828',
        'surface-variant': '#2c3641',
        'secondary-fixed-dim': '#cac6bf',
        tertiary: '#60dcb0',
        'on-secondary-fixed-variant': '#484742',
        'tertiary-container': '#12a47d',
        'error-container': '#93000a',
        'secondary-fixed': '#e6e2db',
        'on-secondary': '#31302c',
        'primary-fixed': '#ffdad9',
        secondary: '#cac6bf',
        background: '#0a141e',
        'primary-container': '#ff525d',
        'inverse-on-surface': '#27313c',
        'surface-bright': '#303a45',
        'on-surface-variant': '#e4bdbc',
        'tertiary-fixed': '#7ff9cc',
        'outline-variant': '#5b403f',
        primary: '#ffb3b2',
        'surface-container-lowest': '#050f19',
        outline: '#ab8887',
        'on-primary-fixed': '#410008',
        'on-primary-fixed-variant': '#92001f',
        'on-tertiary-fixed': '#002116',
        'surface-container': '#17202b',
        'on-tertiary-container': '#003122',
        'primary-fixed-dim': '#ffb3b2',
        'surface-tint': '#ffb3b2',
        surface: '#0a141e',
        'tertiary-fixed-dim': '#60dcb0',
        'surface-dim': '#0a141e',
        'surface-container-low': '#121c27',
        'surface-container-highest': '#2c3641',
        'on-background': '#d9e3f2',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0px',
        lg: '0px',
        xl: '0px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
